-- PASSO 1 - INSERIR OCORRÊNCIA
INSERT INTO SAJADM.ESRHOCORRENCIA VALUES ((SELECT MAX(CDOCORRENCIA) FROM SAJADM.ESRHOCORRENCIA)+1,314878145,7532,TO_DATE('17/08/1983','DD/MM/YYYY'),TO_DATE('17/08/1983','DD/MM/YYYY'),NULL
          ,NULL,NULL,NULL,NULL,NULL,14,'MIGRACAO',SYSDATE,'MIGRACAO',SYSDATE,NULL,'N');

-- PASSO 2 - INSERIR MOTIVO MOVIMENTO
INSERT INTO SAJADM.ESRHMOTIVOMOVIMEN VALUES ((SELECT MAX(CDMOTIVOMOVIMENTO)+1 FROM SAJADM.ESRHMOTIVOMOVIMEN),'Rescisão de Contrato',15,'N',NULL,NULL,NULL,NULL,NULL,'N','N','N','N');

-- PASSO 3 - INSERIR VACÂNCIA
INSERT INTO SAJADM.ESRHVACANCIA VALUES ((SELECT CDOCORRENCIA FROM SAJADM.ESRHOCORRENCIA WHERE CDVINCULO = 7532 AND CDTIPOOCORRENCIA = 14),4,
  (SELECT CDMOTIVOMOVIMENTO FROM SAJADM.ESRHMOTIVOMOVIMEN WHERE DEMOTIVOMOVIMENTO = 'Rescisão de Contrato' AND CDTIPOMOVIMENTO = 15),35,TO_DATE('17/08/1983','DD/MM/YYYY'),'N'
        ,NULL);

-- PASSO 4 - INSERIR DEMISSAO
INSERT INTO SAJADM.ESRHDEMISSAO VALUES ((SELECT CDOCORRENCIA FROM SAJADM.ESRHOCORRENCIA WHERE CDVINCULO = 7532 AND CDTIPOOCORRENCIA = 14),NULL);

-- PASSO 5 - INSERIR OCORRÊNCIA DE VACÂNCIA
UPDATE SAJADM.ESRHPROVIMENTO SET CDOCORREVACANCIA = (SELECT CDOCORRENCIA FROM SAJADM.ESRHOCORRENCIA WHERE CDVINCULO = 7532 AND CDTIPOOCORRENCIA = 14) WHERE CDOCORRENCIA = 72071;

COMMIT;